- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - flameshot
    - zathura
    - zathura-pdf-mupdf
    - zathura-ps
- name: "Git"
  description: "Git applications"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - git
- name: "Password Manager"
  description: "Password managers"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - bitwarden
